name: Implement CI/CD pipeline with a NodeJS app

# Triggers
on:
  push:
    branches:
      - 'main'
    paths:
      - 'backend/**'
      - 'frontend/**'
  workflow_dispatch:
    inputs:
      deploy_backend:
        description: "Deploy Backend"
        required: false
        default: "true"
      deploy_frontend:
        description: "Deploy Frontend"
        required: false
        default: "true"

permissions:
  id-token: write
  contents: read

jobs:
  deploy-backend:
    if: ${{ github.event_name == 'push' || github.event.inputs.deploy_backend == 'true' }}
    environment: dev
    runs-on: ubuntu-24.04

    steps:
      # 1. Clone Repo
      - name: Clone repo
        uses: actions/checkout@v4

      # 2. Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.IAM_ROLE }}
          role-session-name: "${{ github.actor }}-${{ github.run_id }}"

      # 3. Login to ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Build, Tag, and Push Backend Docker Image
      - name: Backend - Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: backend-app
          IMAGE_TAG: ${{ github.sha }}
        working-directory: ./backend
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG   

  deploy-frontend:
    if: ${{ github.event_name == 'push' || github.event.inputs.deploy_frontend == 'true' }}
    environment: dev
    runs-on: ubuntu-24.04

    steps:
      # 1. Clone Repo
      - name: Clone repo
        uses: actions/checkout@v4

      # 2. Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.IAM_ROLE }}
          role-session-name: "${{ github.actor }}-${{ github.run_id }}"

      # 3. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 4. Install Dependencies
      - name: Install Dependencies
        working-directory: ./frontend
        run: npm ci

      # 5. Build App
      - name: Build App
        working-directory: ./frontend
        env:
          VITE_BACKEND_API_URL: ${{ vars.VITE_BACKEND_API_URL }}
          VITE_USER_POOL_ID: ${{ vars.VITE_USER_POOL_ID }}
          VITE_USER_POOL_CLIENT_ID: ${{ vars.VITE_USER_POOL_CLIENT_ID }}
          VITE_AWS_REGION: ${{ vars.AWS_REGION }}
        run: npm run build

      # 6. Deploy to S3
      - name: Deploy to S3
        working-directory: ./frontend
        run: |
          aws s3 sync dist/ s3://spectrex.click --delete
