name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-backend:
    runs-on: ubuntu-24.04
    environment: dev
    
    steps:
      # 1. Clone Repo
      - name: Clone repo
        uses: actions/checkout@v4

      # 2. Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.IAM_ROLE }}
          role-session-name: "${{ github.actor }}-${{ github.run_id }}"

      # 3. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      # 4. Move to the backend directory
      - name: Change Directory to Backend
        run: cd backend

      # 5. Install Dev Dependencies (Build Stage)
      - name: Install Dependencies (Build Stage)
        run: |
          cd backend
          npm ci

      # 6. Run Build
      - name: Run Build
        run: |
          cd backend
          npm run bundle

      # 7. Install Only Production Dependencies (Final Stage)
      - name: Prepare Lambda Package
        run: |
          export LAMBDA_TASK_ROOT="/var/task"
          mkdir -p $LAMBDA_TASK_ROOT
          cp -r backend/dist backend/package.json backend/package-lock.json $LAMBDA_TASK_ROOT/
          cd $LAMBDA_TASK_ROOT
          npm ci --production
          zip -r ../lambda.zip .
          cd ..

      # 8. Upload to S3
      - name: Upload to S3
        run: |
          aws s3 cp lambda.zip s3://test-dev-nscc77-redhat-bucket-test2/lambda.zip
