name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-backend:
    runs-on: ubuntu-24.04
    environment: dev
    
    steps:
      # 1. Clone Repo
      - name: Clone Repository
        uses: actions/checkout@v4

      # 2. Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.IAM_ROLE }}
          role-session-name: "${{ github.actor }}-${{ github.run_id }}"

      # 3. Build the Docker Image
      - name: Build Docker Image
        working-directory: ./backend
        run: |
          docker build -t lambda-backend .

      # 4. Extract Lambda Package from Docker Image
      - name: Extract Lambda Files
        working-directory: ./backend
        run: |
          # Create a temporary container
          CONTAINER_ID=$(docker create lambda-backend)

          # Copy files from the container to the host machine
          docker cp $CONTAINER_ID:/var/task lambda_package

          # Remove the temporary container
          docker rm $CONTAINER_ID

      # 5. Create ZIP File for AWS Lambda
      - name: Create Lambda ZIP
        working-directory: ./backend/lambda_package
        run: |
          zip -r ../lambda.zip .

      # 6. Upload ZIP to S3 for Lambda Deployment
      - name: Upload to S3
        run: |
          aws s3 cp backend/lambda.zip s3://test-dev-nscc77-redhat-bucket-test2/lambda.zip
