# name: Deploy Backend

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'backend/**'
#   workflow_dispatch:

# permissions:
#   id-token: write
#   contents: read

# jobs:
#   deploy-backend:
#     runs-on: ubuntu-24.04
#     environment: dev
    
#     steps:
#       # 1. Clone Repo
#       - name: Clone repo
#         uses: actions/checkout@v4

#       # 2. Configure AWS Credentials
#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           aws-region: ${{ vars.AWS_REGION }}
#           role-to-assume: ${{ vars.IAM_ROLE }}
#           role-session-name: "${{ github.actor }}-${{ github.run_id }}"

#       # 3. Login to ECR
#       - name: Login to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v2

#       # 4. Build, Tag, and Push Docker Image
#       - name: Backend - Build, tag, and push docker image to Amazon ECR
#         env:
#           REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           REPOSITORY: serverless24b-redhat-dev-backend
#           IMAGE_TAG: ${{ github.sha }}
#         working-directory: ./backend
#         run: |
#           docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
#           docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
