name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-frontend:
    runs-on: ubuntu-24.04
    environment: dev
    
    steps:
      # 1. Clone Repo
      - name: Clone repo
        uses: actions/checkout@v4

      # 2. Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.IAM_ROLE }}
          role-session-name: "${{ github.actor }}-${{ github.run_id }}"

      # 6. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 7. Install Dependencies
      - name: Install Dependencies
        working-directory: ./frontend
        run: npm ci

      # 8. Build App
      - name: Build App
        working-directory: ./frontend
        env:
          VITE_BACKEND_API_URL: ${{ vars.VITE_BACKEND_API }}
          VITE_USER_POOL_ID: ${{ vars.VITE_USER_POOL_ID }}
          VITE_USER_POOL_CLIENT_ID: ${{ vars.VITE_USER_POOL_CLIENT_ID }}
          VITE_AWS_REGION: ${{ vars.AWS_REGION }}
        run: npm run build

      # 9. Deploy to S3
      - name: Deploy to S3
        working-directory: ./frontend
        run: |
          aws s3 sync dist/ s3://spectrex.click --delete
