name: Deploy Terraform

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-deploy:
    runs-on: ubuntu-22.04
    environment: dev  
    steps:
      # 1. Clone the repository
      - name: Clone Repo
        uses: actions/checkout@v3
      
      # 2. Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.IAM_ROLE }}
          role-session-name: "${{ github.actor }}-${{ github.run_id }}"

      # 3. Set Terraform Environment Variables
      - name: Set Environment Variables
        run: |
          echo "TF_VAR_acct_id=${{ secrets.ACCT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_aws_region=${{ vars.AWS_REGION }}" >> $GITHUB_ENV

      # 4. Terraform Init, Validate, Plan, and Apply
      - name: Terraform Init, Validate, Plan, and Apply
        working-directory: ./terraform/root-module
        run: |
          terraform init
          terraform validate
          terraform plan -out=tfplan -input=false
          terraform apply -auto-approve tfplan